### ISSUE TITLE
Foliage billboards face camera direction instead of camera location

### ISSUE THREAD

**Issue by theinlein** [dustyroom-studio/quibli-doc#1]
When utilizing the Quibli foliage in VR, I notice the foliage moves with head movement (i.e. the direction the camera is pointing) instead of facing the camera's position as it should. This results in odd-moving foliage as the player looks around.

1. Load "[Demo] Nature" scene
2. Add an XR rig to the scene and deactivate the demo scene's main camera
3. Build project to VR device
4. Move your head

**Expected behavior**
The billboards should face the location of the camera--not the direction the camera is facing. Regardless of the direction the camera is pointing, the billboard orientation should not move if the position of the camera does not move.

 - Quibli version: 1.0.0
 - Unity version: 2020.2.3.10f1]
 - Graphics Pipeline: URP
 - Development OS: Mac
 - Platform: Android
 - Test device: Oculus Quest 2

**Comment by dustyroom-studio** [comment]
Thanks for pointing that out, we're looking into it.

**Comment by dustyroom-studio** [comment]
We've submitted an update (1.0.1) which addresses this issue with a `Billboard Face Camera Position` option in the Foliage shader. Please take a look.

**Comment by theinlein** [comment]
After updating, I did not notice the option in the location shown in the Foliage Shader screenshot in the online documentation. I started a new project so I could import the 1.0.1 version fresh, in case this was due to update issues. However, that project also does not show the option in the shader. Please reference the below screenshot:
![Screen Shot 2021-09-17 at 10 46 24 AM](https://user-images.githubusercontent.com/570937/133803136-0aa60d6e-1a71-452c-9c5f-fdde5ca7b776.png)

**Comment by dustyroom-studio** [comment]
Hi,
Thank you for the screenshot. Do you have any errors in the Console? From the screenshot I can tell that there must have been some importing issues, as the interface should not look like you've got (the parameter names are broken).
Could you please re-import Quibli with prior cache cleaning (Package Manager saves the cache so that sometimes the updates cannot be downloaded). The cache can be found here:

- Mac OS: ~/Library/Unity/Asset Store-5.x (press Shift+Cmd+G in any Finder Window and paste this path)
- Windows: %APPDATA%\Unity\Asset Store-5.x (it is a hidden folder)

When you delete the cache, please, reopen Unity project, go to the Package Manager, locate Quibli in 'My Assets' and try downloading and then importing it once more.

**Comment by dustyroom-studio** [comment]
If you are still having troubles with the Package Manager, please, write us an email to info@dustyroom.com, I'll send you the latest package directly.

**Comment by theinlein** [comment]
Cleaned the cache/existing package, created a new project, re-downloaded, and although the parameter names all appear okay, the new option is still not there. I'll contact you via email to see what we can sort out.

**Comment by dustyroom-studio** [comment]
We've added a new parameter `Billboard Face Camera Position` that should resolve this issue.
A similar parameter will be added to the `Cloud3D` shader in the next update this week.
