### ISSUE TITLE
StylizedLit fails to compile

### ISSUE THREAD

**Issue by haveamission** [dustyroom-studio/quibli-doc#3]
**Describe the bug**
Does not import into a project that was converted to universal render

**To Reproduce**
Start with builtin, convert to URP, try to import library.

**Expected behavior**
Library works as intended

**Screenshots**

![Screen Shot 2021-09-27 at 3 39 21 AM](https://user-images.githubusercontent.com/10475533/134864936-3fc9851f-e23e-488f-94de-d11c5470df40.png)

**Unity details:**
 - Quibli version: 1.0.2
 - Unity version: 2020.3.18f1
 - Graphics Pipeline: URP
 - URP version (if applicable): Unknown
 - Development OS: MacOS

**Build platform:**
 - Platform: PC, Mac and Linux Standalone
 - Test device: Macbook Pro running MacOS Catalina

**Additional context**
May be due to conversion to URP

**Comment by dustyroom-studio** [comment]
Hi,

This might have happened because your project had been started in Built-In RP and converted to URP. 
The first thing you can try is re-importing Quibli:
Please, navigate to **Project** panel -> **Assets** folder -> select **Quibli** -> right click on it -> press **Reimport**. 

If re-importing doesn't help, please, try creating the URP project first. We have a detailed guide [here](https://quibli.dustyroom.com/installation/#importing-quibli).

Please, let us know if the issue still persists.

**Comment by haveamission** [comment]
Ok, I'm out of town now but I'll run some checks in the next few days and see what conditions replicate it

**Comment by haveamission** [comment]
Ok, started with a URP project (NOT a converted one, which did not work) and it works fine. So you have to start with a URP project
