### ISSUE TITLE
Model are not rendering like a sample picture/ movie

### ISSUE THREAD

**Issue by Benny-ka** [dustyroom-studio/quibli-doc#5]
**Describe the bug**
Model are not rendering like a sample picture/ movie.
Some models are not shown in scene.

**To Reproduce**
1. Install Qubili from Package Manager.
2. Import Qubili.
3. Automatic finalizing using Readme script.
4. Check the Demo scene and some models are missing or not rendering properly.

**Expected behavior**
All model are shown in scene and rendered properly.

**Screenshots**
<img width="1278" alt="スクリーンショット 2021-10-20 12 35 58" src="https://user-images.githubusercontent.com/92838279/138025210-9ab501f5-96d0-4285-bf99-a205d5fd5f13.png">

<img width="1277" alt="スクリーンショット 2021-10-20 12 37 10" src="https://user-images.githubusercontent.com/92838279/138025229-e155c1ff-de5e-4273-aa43-d090cd84509e.png">
<img width="1276" alt="スクリーンショット 2021-10-20 12 37 37" src="https://user-images.githubusercontent.com/92838279/138025257-f3d82d17-ae78-4906-bb24-8cb699270b8f.png">
<img width="1279" alt="スクリーンショット 2021-10-20 12 48 57" src="https://user-images.githubusercontent.com/92838279/138025268-f217cbdf-5842-4011-a09f-b0f8d2fc11d2.png">

<img width="1280" alt="スクリーンショット 2021-10-20 12 49 54" src="https://user-images.githubusercontent.com/92838279/138025283-156a1704-8d4f-4224-b6dc-60f738abf074.png">

<img width="1275" alt="スクリーンショット 2021-10-20 12 53 23" src="https://user-images.githubusercontent.com/92838279/138025305-56aabd68-8df1-40b2-a74f-14bf7850f8b1.png">

<img width="1280" alt="スクリーンショット 2021-10-20 12 53 50" src="https://user-images.githubusercontent.com/92838279/138025421-2f4aa7c1-6cb8-4c38-b2ac-d99ef5741511.png">

**Unity details**:
(Use the `Copy` button in your project *Quibli/Readme* file and paste here.)
Quibli version 1.0.3
Unity 2020.3.20f1
Dev platform: OSXEditor
Target platform: StandaloneOSX
URP installed: True, version 10.6.0
Render pipeline: UniversalPipeline,LightweightPipeline
Quality config: Quibli URP Config
Graphics config: Quibli URP Config

**Additional context**
I hope you can help me please.

**Comment by dustyroom-studio** [comment]
Hi, thank you for sharing the details. I've just installed a fresh copy of Quibli 1.0.3 in Unity 2020.3.20, URP version 1.6.0, on the Mac. Everything opens normally, the scenes look identical to the ones on the Asset Store. Here are a few examples.

![quibli_imported_city_scene](https://user-images.githubusercontent.com/74666746/138030942-21f860a9-a5bc-4f37-a6df-b5692fe574bf.png)

![quibli_imported_nature_scene](https://user-images.githubusercontent.com/74666746/138030951-cde3d13d-b0ad-4ecd-b177-07d24a7d514a.png)

![quibli_imported_mugs_scene](https://user-images.githubusercontent.com/74666746/138030957-65e15372-059d-4e61-ab3e-c5d1fea09522.png)

Could you please try doing the following:

  - Something might have gone wrong during the importing of Quibli. Could you please try reimporting it, as described in this [guide](https://quibli.dustyroom.com/installation/#after-importing-quibli-gives-errors)?
  - Have you created your project initially in Built-In RP and upgraded it to URP, please create a URP project from the start.
  - If you have moved the Quibli folder after importing, please, reimport Quibli. It's due to a [Shader Grapth bug](https://quibli.dustyroom.com/faqs/#im-getting-errors-after-moving-the-quibli-folder-from-assets)
  - If nothing helps, please, try reinstalling URP and ShaderGraph packages from the Package Manager.
  - Are there any errors in the Console?

Please, let us know if the issue persists.
