### ISSUE TITLE
Stylized Detail and Stylized Color Grading seems not work.

### ISSUE THREAD

**Issue by DogsLike** [dustyroom-studio/quibli-doc#6]
No matter whether I enable or disable the two components, or change any parameters of the components, there is no difference in the screen. I use unity2021.2 and quibli1.1.0. Is this problem caused by the version, or are these two functions designed in this way?

**Comment by dustyroom-studio** [comment]
Hi,

Do the effects work in the demo scenes provided with the asset?
Please check the documentation on the post effects: https://quibli.dustyroom.com/stylized-detail-post-effect/

**Comment by DogsLike** [comment]
Hi, here is Demo scene picture.

Scene with Stylized Detail Enabled:
![active](https://user-images.githubusercontent.com/5936439/143177650-d0d20704-a3f7-4b22-ab81-b1461578c8c5.png)

Scene with Stylized Detail Disabled:
![off](https://user-images.githubusercontent.com/5936439/143177729-8bb55efe-d08c-4cdd-ac1f-0fe35e43330a.png)

 Stylized Detail Setting:
![settings](https://user-images.githubusercontent.com/5936439/143177811-6bf442a8-76ad-4324-886a-7325cdf36fe1.png)


other settings:
![QQ截图20211124131118](https://user-images.githubusercontent.com/5936439/143178667-8893bd93-1112-4078-af19-54461f756c34.png)

![QQ截图20211124131151](https://user-images.githubusercontent.com/5936439/143178676-64f80230-16da-49d7-a08a-daca67a88cf2.png)



It seems that the component does not work in the demo scene,  through parameters can be changed.

**Comment by dustyroom-studio** [comment]
Thank you for the screenshots. We're looking into this issue and will get back once we get any news.

**Comment by dustyroom-studio** [comment]
@DogsLike We found a workaround and uploaded an update to the Asset Store. Please clear Package Manager cache using Assets/Quibli/Readme, re-download and re-import Quibli.
This should download today's update. Does that resolve the issue?

**Comment by DogsLike** [comment]
It seems that I can't download the latest package. After I click clean cache, I click download. After the download, the package manager prompts me that I need to update. After the update is completed, it still prompts me that I need to update. The package I downloaded is still the previous version.Both versions are 1.1.0. Is that the reason?


Quibli version 1.1.0
Unity 2021.2.2f1c1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.1
Render pipeline: UniversalPipeline
Quality config: Quibli URP Config
Graphics config: Quibli URP Config

**Comment by dustyroom-studio** [comment]
I have just tried updating Quibli in the project where I tested your initial issue, and it successfully did so. I don't think it is related to the fact it is still a 1.1.0 version of Quibli.

Could you please try cleaning the cache, exiting Unity, loading an official stable version instead of an 'fc' version of Unity, opening Package Manager downloading and importing Quibli? The latest stable version is 2021.2.3f1.

![unity-hub-latest-stable-2021_2-version](https://user-images.githubusercontent.com/74666746/143392653-2bf3d2ce-c125-4df1-b0b2-51215504d507.png)

Also, you can try deleting the cache manually here (press Win+R to open ‘Run’ window and paste the path below) and restarting Unity.
Windows: %APPDATA%\Unity\Asset Store-5.x
The folder you are supposed to delete is called 'Dustyroom'.

**Comment by DogsLike** [comment]
OK, I'll try. Thanks.

**Comment by DogsLike** [comment]
It works! Thank god and thank you. In fact, I've spent some time looking for post processing for anime rendering. These two components will help a lot. thank again.
